name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{toJson(github.event.commits)}}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{join(github.event.commits.*.message, '\n')}}
        run: echo "$COMMIT_MESSAGES"
